"""Role testing files using testinfra."""
import pytest


@pytest.mark.parametrize("files", [
    "/etc/yum.repos.d/CentOS-Base.repo",
    "/etc/yum.repos.d/epel.repo"
])
def test_repo_files(host, files):
    f = host.file(files)
    assert f.exists
    assert f.is_file


@pytest.mark.parametrize("files", [
    "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"
])
def test_rpm_files(host, files):
    f = host.file(files)
    assert f.exists
    assert f.is_file


def test_epel_content(host):
    conf = host.file('/etc/yum.repos.d/epel.repo')
    conf_content = conf.content

    expected = [
        b'#',
        b'# Custom Yum Repositories',
        b'# Ansible managed: Do NOT edit this file manually!',
        b'#',
        b'[epel]',
        b'name=epel',
        b'metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir',
        b'enabled=1',
        b'countme=1',
        b'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7',
        b'gpgcheck=1'
    ]

    for line in expected:
        assert line in conf_content
