---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/centos/centos:7
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: rhel7
