---
ansible_python_interpreter: python3
yum_repo_common_files:
  - name: CentOS-Base
    repos:
      - name: base
        mirrorlist: 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra'
        gpgcheck: 1
        enabled: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-{{ ansible_distribution_major_version }}
      - name: updates
        mirrorlist: 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra'
        gpgcheck: 1
        enabled: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-{{ ansible_distribution_major_version }}
  - name: epel
    repos:
      - name: epel
        metalink: 'https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir'
        enabled: 1
        countme: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        gpgcheck: 1

#yum_repo_additional_files:
#  - name: docker-ce
#    repos:
#      - name: 'docker-ce-stable'
#        baseurl: 'https://download.docker.com/linux/centos/$releasever/$basearch/stable'
#        gpgcheck: 1
#        enabled: 1
#        gpgkey: https://download.docker.com/linux/centos/gpg

rpm_keys:
  - name: epel
    url: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    saved_path: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present

package_manager_config:
  - name: main
    cachedir: /var/cache/yum/$basearch/$releasever
    keepcache: 0
    debuglevel: 2
    logfile: /var/log/yum.log
    exactarch: 1
    obsoletes: 1
    gpgcheck: 1
    plugins: 1
    installonly_limit: 5
    bugtracker_url: http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
    distroverpkg: centos-release
